### ISSUE TITLE
Kong api is not clear, the sni is not update correctly.

### ISSUE THREAD

**Issue by xiaods** [luispabon/kong-certbot-agent#6]
<img width="826" alt="2018-08-07 1 17 34" src="https://user-images.githubusercontent.com/37678/43755796-5e9415fc-9a44-11e8-9ed9-443a56fb30aa.png">

kong-certbot-agent update done, then the kong have no sni for the key.

**Comment by luispabon** [comment]
Thank you Xiao, I believe this interface might have changed recently. I'll push a fix.

**Comment by xiaods** [comment]
@luispabon i am very confuse for the api readme. it clarify the parameter is array, but the sample also use string to as snis field values, it caused me confuse.

**Comment by luispabon** [comment]
Closed via https://github.com/luispabon/kong-certbot-agent/pull/7.
